### PR TITLE
RStudio-Server 2023.12.1

### PR DESCRIPTION
**Pull request by camarocico**
Version of RStudio-Server for R 4.3.2 on the webportal.

### CODE REVIEW

**Comment by Neves-P** [comment]
I'll do this right after https://github.com/rug-cit-hpc/hb-rstudio_server/pull/5 is merged. I'm still waiting for the tst-idp access so I can log in the test portal.

**Comment by camarocico** [comment]
@Neves-P 
You can use the production machine, in the sandbox mode. I've made you a developer, so you can do the following:

- create the `dev` folder on Habrok:
  `mkdir -p $HOME/ondemand/dev`
- go into that folder:
  `cd $HOME/ondemand/dev`
- and clone the RStudio-Server app:
  `git clone git@github.com:rug-cit-hpc/hb-rstudio_server.git`
- you should see a Develop menu item, with a sandbox subitem; your particular versions of the apps are in there (from `$HOME/ondemand/dev`). Switch to develop to see that branch.

**Comment by Neves-P** [comment]
Thanks for the instructions, got it to work!

Not getting the expected RStudio version, though, this seems like an even more recent (2024.04) one using R 4.3.2:
image

And an older one (2023.11), using R 4.2.1: 
image

Unless these aren't the version numbers and I'm just confused 😅

**Comment by camarocico** [comment]
Yeah, I have the same thing, don't know why it shows the installation month...

**Comment by Neves-P** [comment]
Strange! But I guess if we want "Spotted Wakerobin" and "Ocean Storm" then I'd say it's good to go 😃

**Pull request merged**
